# Generated by Django 3.2 on 2023-08-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='readed status'),
        ),
    ]
