# Generated by Django 3.2 on 2023-08-10 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_is_readed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='post',
            name='is_readed',
            field=models.ManyToManyField(related_name='is_readed', to=settings.AUTH_USER_MODEL, verbose_name='readed status'),
        ),
    ]
