# Generated by Django 3.2 on 2023-08-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20230810_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_readed',
        ),
        migrations.CreateModel(
            name='ReadedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_readed', to='blog.post', verbose_name='post readed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_readed', to=settings.AUTH_USER_MODEL, verbose_name='user readed')),
            ],
        ),
    ]
