# Generated by Django 3.2 on 2023-08-10 12:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230810_1600'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='readedpost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_post'),
        ),
        migrations.AddConstraint(
            model_name='readedpost',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('post')), name='check_self_post'),
        ),
    ]
